dependencies = [
    "fastapi>=0.122.0",
    "sqlmodel>=0.0.27",
    "uvicorn>=0.38.0",

    "python-jose[cryptography]>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "bcrypt>=4.0.1",
    "pydantic-settings>=2.0.0",
    "python-multipart>=0.0.9",
]
